version: "2"
environment:
  - TAG: fedora
services:
  otp:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/cloudian/build-otp:${TAG}
    hostname: otp000
    privileged: true
    dns:
      - 127.0.0.1
      - 8.8.8.8
    dns_search:
      - localdomain
    volumes:
      - ~/.ssh:/home/worker/.ssh
